const data = {
    lat:
        47.1604,
    lon:
        27.6268,
    timezone:
        "Europe/Bucharest",
    timezone_offset:
        10800,
    current:
    {
        dt:
            1618219710,
        sunrise:
            1618198014,
        sunset:
            1618246391,
        temp:
            16.19,
        feels_like:
            14.57,
        pressure:
            1021,
        humidity:
            27,
        dew_point:
            -2.49,
        uvi:
            4.25,
        clouds:
            0,
        visibility:
            10000,
        wind_speed:
            1.54,
        wind_deg:
            150,
        weather:
            [
                {
                    id:
                        800,
                    main:
                        "Clear",
                    description:
                        "clear sky",
                    icon:
                        "01d"
                }
            ]
    },
    hourly:
        [
            {
                dt:
                    1618218000,
                temp:
                    16.19,
                feels_like:
                    14.57,
                pressure:
                    1021,
                humidity:
                    27,
                dew_point:
                    -2.49,
                uvi:
                    4.25,
                clouds:
                    0,
                visibility:
                    10000,
                wind_speed:
                    1.56,
                wind_deg:
                    117,
                wind_gust:
                    1.74,
                weather:
                    [
                        {
                            id:
                                800,
                            main:
                                "Clear",
                            description:
                                "clear sky",
                            icon:
                                "01d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618221600,
                temp:
                    16.27,
                feels_like:
                    14.71,
                pressure:
                    1021,
                humidity:
                    29,
                dew_point:
                    -1.57,
                uvi:
                    4.72,
                clouds:
                    0,
                visibility:
                    10000,
                wind_speed:
                    1.16,
                wind_deg:
                    129,
                wind_gust:
                    1.2,
                weather:
                    [
                        {
                            id:
                                800,
                            main:
                                "Clear",
                            description:
                                "clear sky",
                            icon:
                                "01d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618225200,
                temp:
                    16.71,
                feels_like:
                    15.19,
                pressure:
                    1021,
                humidity:
                    29,
                dew_point:
                    -1.23,
                uvi:
                    4.5,
                clouds:
                    0,
                visibility:
                    10000,
                wind_speed:
                    0.73,
                wind_deg:
                    138,
                wind_gust:
                    0.82,
                weather:
                    [
                        {
                            id:
                                500,
                            main:
                                "Rain",
                            description:
                                "light rain",
                            icon:
                                "10d"
                        }
                    ],
                pop:
                    0.2,
                rain:
                    { '1h': 0.1 },
            },
            {
                dt:
                    1618228800,
                temp:
                    17.29,
                feels_like:
                    15.86,
                pressure:
                    1020,
                humidity:
                    30,
                dew_point:
                    -0.38,
                uvi:
                    3.67,
                clouds:
                    1,
                visibility:
                    10000,
                wind_speed:
                    0.56,
                wind_deg:
                    116,
                wind_gust:
                    0.67,
                weather:
                    [
                        {
                            id:
                                800,
                            main:
                                "Clear",
                            description:
                                "clear sky",
                            icon:
                                "01d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618232400,
                temp:
                    17.81,
                feels_like:
                    16.43,
                pressure:
                    1020,
                humidity:
                    30,
                dew_point:
                    0.02,
                uvi:
                    2.52,
                clouds:
                    6,
                visibility:
                    10000,
                wind_speed:
                    0.52,
                wind_deg:
                    71,
                wind_gust:
                    0.57,
                weather:
                    [
                        {
                            id:
                                800,
                            main:
                                "Clear",
                            description:
                                "clear sky",
                            icon:
                                "01d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618236000,
                temp:
                    18.06,
                feels_like:
                    16.7,
                pressure:
                    1019,
                humidity:
                    30,
                dew_point:
                    0.22,
                uvi:
                    1.41,
                clouds:
                    16,
                visibility:
                    10000,
                wind_speed:
                    0.8,
                wind_deg:
                    63,
                wind_gust:
                    0.65,
                weather:
                    [
                        {
                            id:
                                801,
                            main:
                                "Clouds",
                            description:
                                "few clouds",
                            icon:
                                "02d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618239600,
                temp:
                    17.71,
                feels_like:
                    16.35,
                pressure:
                    1019,
                humidity:
                    31,
                dew_point:
                    0.5,
                uvi:
                    0.59,
                clouds:
                    25,
                visibility:
                    10000,
                wind_speed:
                    0.73,
                wind_deg:
                    71,
                wind_gust:
                    0.72,
                weather:
                    [
                        {
                            id:
                                802,
                            main:
                                "Clouds",
                            description:
                                "scattered clouds",
                            icon:
                                "03d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618243200,
                temp:
                    16.06,
                feels_like:
                    14.82,
                pressure:
                    1019,
                humidity:
                    42,
                dew_point:
                    2.92,
                uvi:
                    0.16,
                clouds:
                    37,
                visibility:
                    10000,
                wind_speed:
                    1.14,
                wind_deg:
                    78,
                wind_gust:
                    1.14,
                weather:
                    [
                        {
                            id:
                                802,
                            main:
                                "Clouds",
                            description:
                                "scattered clouds",
                            icon:
                                "03d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618246800,
                temp:
                    13.76,
                feels_like:
                    12.31,
                pressure:
                    1020,
                humidity:
                    43,
                dew_point:
                    1.34,
                uvi:
                    0,
                clouds:
                    46,
                visibility:
                    10000,
                wind_speed:
                    1.7,
                wind_deg:
                    94,
                wind_gust:
                    1.71,
                weather:
                    [
                        {
                            id:
                                802,
                            main:
                                "Clouds",
                            description:
                                "scattered clouds",
                            icon:
                                "03n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618250400,
                temp:
                    12.9,
                feels_like:
                    11.45,
                pressure:
                    1020,
                humidity:
                    46,
                dew_point:
                    1.4,
                uvi:
                    0,
                clouds:
                    55,
                visibility:
                    10000,
                wind_speed:
                    1.55,
                wind_deg:
                    106,
                wind_gust:
                    1.57,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618254000,
                temp:
                    12.24,
                feels_like:
                    10.8,
                pressure:
                    1020,
                humidity:
                    49,
                dew_point:
                    1.61,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    1.88,
                wind_deg:
                    118,
                wind_gust:
                    1.86,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618257600,
                temp:
                    11.43,
                feels_like:
                    10.04,
                pressure:
                    1020,
                humidity:
                    54,
                dew_point:
                    2.25,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    2.16,
                wind_deg:
                    127,
                wind_gust:
                    2.97,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618261200,
                temp:
                    10.72,
                feels_like:
                    9.39,
                pressure:
                    1020,
                humidity:
                    59,
                dew_point:
                    2.68,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    2.07,
                wind_deg:
                    135,
                wind_gust:
                    2.08,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618264800,
                temp:
                    10.26,
                feels_like:
                    8.93,
                pressure:
                    1020,
                humidity:
                    61,
                dew_point:
                    2.84,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    2.1,
                wind_deg:
                    133,
                wind_gust:
                    2.17,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618268400,
                temp:
                    9.74,
                feels_like:
                    8.97,
                pressure:
                    1020,
                humidity:
                    63,
                dew_point:
                    2.82,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    1.9,
                wind_deg:
                    140,
                wind_gust:
                    1.93,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618272000,
                temp:
                    9.24,
                feels_like:
                    8.39,
                pressure:
                    1019,
                humidity:
                    65,
                dew_point:
                    2.73,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    1.9,
                wind_deg:
                    135,
                wind_gust:
                    1.85,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618275600,
                temp:
                    9.06,
                feels_like:
                    8.51,
                pressure:
                    1019,
                humidity:
                    66,
                dew_point:
                    2.66,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    1.56,
                wind_deg:
                    140,
                wind_gust:
                    1.58,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618279200,
                temp:
                    8.72,
                feels_like:
                    8.34,
                pressure:
                    1019,
                humidity:
                    66,
                dew_point:
                    2.54,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    1.37,
                wind_deg:
                    138,
                wind_gust:
                    1.35,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618282800,
                temp:
                    8.17,
                feels_like:
                    8.17,
                pressure:
                    1019,
                humidity:
                    68,
                dew_point:
                    2.33,
                uvi:
                    0,
                clouds:
                    91,
                visibility:
                    10000,
                wind_speed:
                    1.25,
                wind_deg:
                    123,
                wind_gust:
                    1.23,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618286400,
                temp:
                    8.21,
                feels_like:
                    8.21,
                pressure:
                    1019,
                humidity:
                    69,
                dew_point:
                    2.69,
                uvi:
                    0,
                clouds:
                    76,
                visibility:
                    10000,
                wind_speed:
                    1.13,
                wind_deg:
                    119,
                wind_gust:
                    1.11,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618290000,
                temp:
                    10.27,
                feels_like:
                    9,
                pressure:
                    1019,
                humidity:
                    63,
                dew_point:
                    3.4,
                uvi:
                    0.41,
                clouds:
                    63,
                visibility:
                    10000,
                wind_speed:
                    0.98,
                wind_deg:
                    133,
                wind_gust:
                    1.29,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618293600,
                temp:
                    12.27,
                feels_like:
                    11.01,
                pressure:
                    1019,
                humidity:
                    56,
                dew_point:
                    3.58,
                uvi:
                    1.11,
                clouds:
                    54,
                visibility:
                    10000,
                wind_speed:
                    1.42,
                wind_deg:
                    124,
                wind_gust:
                    1.72,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618297200,
                temp:
                    14.05,
                feels_like:
                    12.84,
                pressure:
                    1019,
                humidity:
                    51,
                dew_point:
                    3.77,
                uvi:
                    2.19,
                clouds:
                    15,
                visibility:
                    10000,
                wind_speed:
                    1.86,
                wind_deg:
                    130,
                wind_gust:
                    2.09,
                weather:
                    [
                        {
                            id:
                                801,
                            main:
                                "Clouds",
                            description:
                                "few clouds",
                            icon:
                                "02d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618300800,
                temp:
                    15.52,
                feels_like:
                    14.33,
                pressure:
                    1018,
                humidity:
                    46,
                dew_point:
                    3.79,
                uvi:
                    3.4,
                clouds:
                    34,
                visibility:
                    10000,
                wind_speed:
                    2.19,
                wind_deg:
                    140,
                wind_gust:
                    2.33,
                weather:
                    [
                        {
                            id:
                                802,
                            main:
                                "Clouds",
                            description:
                                "scattered clouds",
                            icon:
                                "03d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618304400,
                temp:
                    16.7,
                feels_like:
                    15.52,
                pressure:
                    1018,
                humidity:
                    42,
                dew_point:
                    3.57,
                uvi:
                    4.38,
                clouds:
                    51,
                visibility:
                    10000,
                wind_speed:
                    2.27,
                wind_deg:
                    139,
                wind_gust:
                    2.2,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618308000,
                temp:
                    17.48,
                feels_like:
                    16.3,
                pressure:
                    1017,
                humidity:
                    39,
                dew_point:
                    3.19,
                uvi:
                    4.76,
                clouds:
                    63,
                visibility:
                    10000,
                wind_speed:
                    2.39,
                wind_deg:
                    133,
                wind_gust:
                    2.19,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618311600,
                temp:
                    18.08,
                feels_like:
                    16.91,
                pressure:
                    1017,
                humidity:
                    37,
                dew_point:
                    3.08,
                uvi:
                    4.53,
                clouds:
                    70,
                visibility:
                    10000,
                wind_speed:
                    2.7,
                wind_deg:
                    121,
                wind_gust:
                    2.39,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618315200,
                temp:
                    18.36,
                feels_like:
                    17.19,
                pressure:
                    1016,
                humidity:
                    36,
                dew_point:
                    3.07,
                uvi:
                    3.71,
                clouds:
                    75,
                visibility:
                    10000,
                wind_speed:
                    2.95,
                wind_deg:
                    120,
                wind_gust:
                    2.68,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618318800,
                temp:
                    18.31,
                feels_like:
                    17.14,
                pressure:
                    1016,
                humidity:
                    36,
                dew_point:
                    3.09,
                uvi:
                    2.31,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    3.21,
                wind_deg:
                    118,
                wind_gust:
                    2.95,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618322400,
                temp:
                    17.97,
                feels_like:
                    16.81,
                pressure:
                    1015,
                humidity:
                    38,
                dew_point:
                    3.44,
                uvi:
                    1.29,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    3.65,
                wind_deg:
                    118,
                wind_gust:
                    3.51,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618326000,
                temp:
                    17.07,
                feels_like:
                    16.03,
                pressure:
                    1015,
                humidity:
                    46,
                dew_point:
                    5.08,
                uvi:
                    0.54,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    4.1,
                wind_deg:
                    112,
                wind_gust:
                    5.5,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618329600,
                temp:
                    15.2,
                feels_like:
                    14.16,
                pressure:
                    1015,
                humidity:
                    53,
                dew_point:
                    5.4,
                uvi:
                    0.14,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    4.5,
                wind_deg:
                    111,
                wind_gust:
                    8.27,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618333200,
                temp:
                    13.46,
                feels_like:
                    12.35,
                pressure:
                    1015,
                humidity:
                    57,
                dew_point:
                    4.91,
                uvi:
                    0,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    4.29,
                wind_deg:
                    111,
                wind_gust:
                    9.29,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618336800,
                temp:
                    12.76,
                feels_like:
                    11.66,
                pressure:
                    1015,
                humidity:
                    60,
                dew_point:
                    4.87,
                uvi:
                    0,
                clouds:
                    99,
                visibility:
                    10000,
                wind_speed:
                    4.45,
                wind_deg:
                    117,
                wind_gust:
                    10.21,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618340400,
                temp:
                    11.93,
                feels_like:
                    10.9,
                pressure:
                    1015,
                humidity:
                    66,
                dew_point:
                    5.57,
                uvi:
                    0,
                clouds:
                    97,
                visibility:
                    10000,
                wind_speed:
                    4.83,
                wind_deg:
                    130,
                wind_gust:
                    10.39,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618344000,
                temp:
                    10.89,
                feels_like:
                    9.91,
                pressure:
                    1015,
                humidity:
                    72,
                dew_point:
                    5.7,
                uvi:
                    0,
                clouds:
                    94,
                visibility:
                    10000,
                wind_speed:
                    4.14,
                wind_deg:
                    136,
                wind_gust:
                    9.92,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618347600,
                temp:
                    10.14,
                feels_like:
                    9.14,
                pressure:
                    1015,
                humidity:
                    74,
                dew_point:
                    5.48,
                uvi:
                    0,
                clouds:
                    90,
                visibility:
                    10000,
                wind_speed:
                    3.87,
                wind_deg:
                    138,
                wind_gust:
                    8.96,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618351200,
                temp:
                    9.56,
                feels_like:
                    7.54,
                pressure:
                    1015,
                humidity:
                    75,
                dew_point:
                    5.05,
                uvi:
                    0,
                clouds:
                    88,
                visibility:
                    10000,
                wind_speed:
                    3.83,
                wind_deg:
                    135,
                wind_gust:
                    8.32,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618354800,
                temp:
                    8.78,
                feels_like:
                    6.57,
                pressure:
                    1015,
                humidity:
                    77,
                dew_point:
                    4.66,
                uvi:
                    0,
                clouds:
                    85,
                visibility:
                    10000,
                wind_speed:
                    3.87,
                wind_deg:
                    135,
                wind_gust:
                    7.76,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618358400,
                temp:
                    8.1,
                feels_like:
                    5.7,
                pressure:
                    1014,
                humidity:
                    79,
                dew_point:
                    4.32,
                uvi:
                    0,
                clouds:
                    79,
                visibility:
                    10000,
                wind_speed:
                    3.93,
                wind_deg:
                    136,
                wind_gust:
                    8.23,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618362000,
                temp:
                    7.66,
                feels_like:
                    5.19,
                pressure:
                    1014,
                humidity:
                    80,
                dew_point:
                    4.02,
                uvi:
                    0,
                clouds:
                    71,
                visibility:
                    10000,
                wind_speed:
                    3.87,
                wind_deg:
                    139,
                wind_gust:
                    8.8,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618365600,
                temp:
                    7.17,
                feels_like:
                    4.86,
                pressure:
                    1014,
                humidity:
                    81,
                dew_point:
                    3.83,
                uvi:
                    0,
                clouds:
                    72,
                visibility:
                    10000,
                wind_speed:
                    3.4,
                wind_deg:
                    140,
                wind_gust:
                    7.53,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618369200,
                temp:
                    6.67,
                feels_like:
                    4.56,
                pressure:
                    1014,
                humidity:
                    83,
                dew_point:
                    3.71,
                uvi:
                    0,
                clouds:
                    79,
                visibility:
                    10000,
                wind_speed:
                    2.93,
                wind_deg:
                    137,
                wind_gust:
                    6.41,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04n"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618372800,
                temp:
                    6.78,
                feels_like:
                    4.92,
                pressure:
                    1014,
                humidity:
                    83,
                dew_point:
                    3.88,
                uvi:
                    0.01,
                clouds:
                    84,
                visibility:
                    10000,
                wind_speed:
                    2.62,
                wind_deg:
                    136,
                wind_gust:
                    6.43,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618376400,
                temp:
                    8.18,
                feels_like:
                    6.36,
                pressure:
                    1015,
                humidity:
                    77,
                dew_point:
                    4.16,
                uvi:
                    0.04,
                clouds:
                    88,
                visibility:
                    10000,
                wind_speed:
                    2.94,
                wind_deg:
                    138,
                wind_gust:
                    6.55,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618380000,
                temp:
                    9.76,
                feels_like:
                    7.77,
                pressure:
                    1015,
                humidity:
                    70,
                dew_point:
                    4.31,
                uvi:
                    0.11,
                clouds:
                    90,
                visibility:
                    10000,
                wind_speed:
                    3.86,
                wind_deg:
                    148,
                wind_gust:
                    6.52,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618383600,
                temp:
                    11.2,
                feels_like:
                    10.07,
                pressure:
                    1015,
                humidity:
                    65,
                dew_point:
                    4.55,
                uvi:
                    0.2,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    4.38,
                wind_deg:
                    157,
                wind_gust:
                    6.47,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            },
            {
                dt:
                    1618387200,
                temp:
                    12.41,
                feels_like:
                    11.3,
                pressure:
                    1014,
                humidity:
                    61,
                dew_point:
                    4.81,
                uvi:
                    0.3,
                clouds:
                    100,
                visibility:
                    10000,
                wind_speed:
                    4.33,
                wind_deg:
                    157,
                wind_gust:
                    5.75,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                pop:
                    0
            }
        ],
    daily:
        [
            {
                dt:
                    1618221600,
                sunrise:
                    1618198014,
                sunset:
                    1618246391,
                temp:
                {
                    day:
                        16.27,
                    min:
                        5.95,
                    max:
                        18.06,
                    night:
                        11.43,
                    eve:
                        16.06,
                    morn:
                        6.07
                },
                feels_like:
                {
                    day:
                        14.71,
                    night:
                        6.07,
                    eve:
                        14.82,
                    morn:
                        6.07
                },
                pressure:
                    1021,
                humidity:
                    29,
                dew_point:
                    -1.57,
                wind_speed:
                    1.16,
                wind_deg:
                    129,
                weather:
                    [
                        {
                            id:
                                500,
                            main:
                                "Rain",
                            description:
                                "light rain",
                            icon:
                                "10d"
                        }
                    ],
                clouds:
                    0,
                pop:
                    0.2,
                rain:
                    0.1,
                uvi:
                    4.72
            },
            {
                dt:
                    1618308000,
                sunrise:
                    1618284300,
                sunset:
                    1618332875,
                temp:
                {
                    day:
                        17.48,
                    min:
                        8.17,
                    max:
                        18.36,
                    night:
                        10.89,
                    eve:
                        15.2,
                    morn:
                        8.21
                },
                feels_like:
                {
                    day:
                        16.3,
                    night:
                        8.21,
                    eve:
                        14.16,
                    morn:
                        8.21
                },
                pressure:
                    1017,
                humidity:
                    39,
                dew_point:
                    3.19,
                wind_speed:
                    2.39,
                wind_deg:
                    133,
                weather:
                    [
                        {
                            id:
                                803,
                            main:
                                "Clouds",
                            description:
                                "broken clouds",
                            icon:
                                "04d"
                        }
                    ],
                clouds:
                    63,
                pop:
                    0,
                uvi:
                    4.76
            },
            {
                dt:
                    1618394400,
                sunrise:
                    1618370587,
                sunset:
                    1618419358,
                temp:
                {
                    day:
                        13.78,
                    min:
                        6.31,
                    max:
                        13.78,
                    night:
                        6.31,
                    eve:
                        10.16,
                    morn:
                        6.78
                },
                feels_like:
                {
                    day:
                        12.7,
                    night:
                        4.92,
                    eve:
                        9.37,
                    morn:
                        4.92
                },
                pressure:
                    1013,
                humidity:
                    57,
                dew_point:
                    5.31,
                wind_speed:
                    4.1,
                wind_deg:
                    143,
                weather:
                    [
                        {
                            id:
                                500,
                            main:
                                "Rain",
                            description:
                                "light rain",
                            icon:
                                "10d"
                        }
                    ],
                clouds:
                    100,
                pop:
                    0.99,
                rain:
                    3.8,
                uvi:
                    0.89
            },
            {
                dt:
                    1618480800,
                sunrise:
                    1618456874,
                sunset:
                    1618505841,
                temp:
                {
                    day:
                        3.65,
                    min:
                        3.65,
                    max:
                        5.55,
                    night:
                        3.77,
                    eve:
                        4.02,
                    morn:
                        3.95
                },
                feels_like:
                {
                    day:
                        -0.54,
                    night:
                        -0.29,
                    eve:
                        0,
                    morn:
                        -0.29
                },
                pressure:
                    1016,
                humidity:
                    96,
                dew_point:
                    2.74,
                wind_speed:
                    5.39,
                wind_deg:
                    308,
                weather:
                    [
                        {
                            id:
                                500,
                            main:
                                "Rain",
                            description:
                                "light rain",
                            icon:
                                "10d"
                        }
                    ],
                clouds:
                    100,
                pop:
                    1,
                rain:
                    7.19,
                uvi:
                    0.69
            },
            {
                dt:
                    1618567200,
                sunrise:
                    1618543163,
                sunset:
                    1618592324,
                temp:
                {
                    day:
                        5.6,
                    min:
                        3.1,
                    max:
                        8.34,
                    night:
                        5.4,
                    eve:
                        7.92,
                    morn:
                        3.1
                },
                feels_like:
                {
                    day:
                        1.71,
                    night:
                        -1.56,
                    eve:
                        5.16,
                    morn:
                        -1.56
                },
                pressure:
                    1017,
                humidity:
                    84,
                dew_point:
                    2.65,
                wind_speed:
                    5.86,
                wind_deg:
                    301,
                weather:
                    [
                        {
                            id:
                                500,
                            main:
                                "Rain",
                            description:
                                "light rain",
                            icon:
                                "10d"
                        }
                    ],
                clouds:
                    100,
                pop:
                    0.61,
                rain:
                    1.25,
                uvi:
                    2.41
            },
            {
                dt:
                    1618653600,
                sunrise:
                    1618629452,
                sunset:
                    1618678808,
                temp:
                {
                    day:
                        6.27,
                    min:
                        3.44,
                    max:
                        7.58,
                    night:
                        6.02,
                    eve:
                        7.58,
                    morn:
                        3.44
                },
                feels_like:
                {
                    day:
                        4.9,
                    night:
                        3.44,
                    eve:
                        6.74,
                    morn:
                        3.44
                },
                pressure:
                    1020,
                humidity:
                    83,
                dew_point:
                    3.25,
                wind_speed:
                    1.95,
                wind_deg:
                    290,
                weather:
                    [
                        {
                            id:
                                804,
                            main:
                                "Clouds",
                            description:
                                "overcast clouds",
                            icon:
                                "04d"
                        }
                    ],
                clouds:
                    100,
                pop:
                    0.06,
                uvi:
                    3
            },
            {
                dt:
                    1618740000,
                sunrise:
                    1618715742,
                sunset:
                    1618765291,
                temp:
                {
                    day:
                        10.24,
                    min:
                        4.89,
                    max:
                        12.49,
                    night:
                        7.72,
                    eve:
                        11.37,
                    morn:
                        4.89
                },
                feels_like:
                {
                    day:
                        9.15,
                    night:
                        4.89,
                    eve:
                        10.23,
                    morn:
                        4.89
                },
                pressure:
                    1025,
                humidity:
                    70,
                dew_point:
                    4.64,
                wind_speed:
                    2.88,
                wind_deg:
                    70,
                weather:
                    [
                        {
                            id:
                                500,
                            main:
                                "Rain",
                            description:
                                "light rain",
                            icon:
                                "10d"
                        }
                    ],
                clouds:
                    100,
                pop:
                    0.34,
                rain:
                    0.4,
                uvi:
                    3
            },
            {
                dt:
                    1618826400,
                sunrise:
                    1618802033,
                sunset:
                    1618851775,
                temp:
                {
                    day:
                        8.4,
                    min:
                        4.77,
                    max:
                        11.39,
                    night:
                        8.21,
                    eve:
                        11.28,
                    morn:
                        4.77
                },
                feels_like:
                {
                    day:
                        5.71,
                    night:
                        2.8,
                    eve:
                        10.11,
                    morn:
                        2.8
                },
                pressure:
                    1023,
                humidity:
                    82,
                dew_point:
                    5.16,
                wind_speed:
                    4.72,
                wind_deg:
                    88,
                weather:
                    [
                        {
                            id:
                                500,
                            main:
                                "Rain",
                            description:
                                "light rain",
                            icon:
                                "10d"
                        }
                    ],
                clouds:
                    100,
                pop:
                    0.78,
                rain:
                    2.1,
                uvi:
                    3
            }
        ]
}

export default data;